apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: analytics
      host: clickhouse
      port: 9000
      protocol: native
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: showcase
